### ISSUE TITLE
Support for ECDSA accounts

### ISSUE THREAD

**Issue by ERussel** [airgap-it/beacon-ios-sdk#10]
SDK supports only accounts with public keys of [32 byte](https://github.com/airgap-it/beacon-ios-sdk/blob/develop/Sources/BlockchainSubstrate/Wallet.swift#L26).

However Substrate also supports [ECDSA signatures on secp256k1](https://wiki.polkadot.network/docs/learn-keys#account-keys) which has public keys 33 bytes long

**Comment by jsamol** [comment]
We've resigned from providing the address generation functionality in the SDK. From now on (`v3.1.0-beta.0`) it's the developer's responsibility to provide the address when responding to a permission request.
