### ISSUE TITLE
[Feature Request]: Beacon.P2PPeer init with url

### ISSUE THREAD

**Issue by simonmcl** [airgap-it/beacon-ios-sdk#13]
When scanning a QR code and receiving a URL with a tzip standard, it would be great if the Beacon SDK took care of all of the processing and logic and just had an init that took in a URL. It takes a lot of experimentation and research to figure out what needs to be done with the URL

```
Beacon.P2PPeer(initWithURL: URL)
```

**Comment by simonmcl** [comment]
When copying the contents of the QRCode (when scanning is not available), you only get the Base58 encoded data. Again, it would be useful if there was an init for this also

**Comment by jsamol** [comment]
We've just released v3.2.0 which comes with some new features, including the new pairing interface. Now, you can pair a new peer using a serialized pairing request (a copied content of a QR code) with [`Beacon.WalletClient#pair(with:/*String*/,completion:)`](https://github.com/airgap-it/beacon-ios-sdk/blob/develop/Sources/ClientWallet/Beacon/WalletClient.swift#L57).
