### ISSUE TITLE
[Feature Request]: Function to convert signPayload body into human readable string

### ISSUE THREAD

**Issue by simonmcl** [airgap-it/beacon-ios-sdk#14]
When receiving a signPayload request, I can't find anything to help me convert the hex into a human readable string. I roughly followed a snippet on the Taquito docs to figure out what needs to be done, but i'm not sure if it will cover all cases, if there are tzips etc. And I can't use taquito to parse it.

It would be great if the SDK did this for you, by having a "humanReadable" string property as part of the signPayload request object

**Comment by jsamol** [comment]
Hi! We have to reject this request as the functionality you're asking for is not in Beacon's scope. Beacon is a communication layer and it's not its responsibility to interpret the data that it transmits. The requested functionality is better suited for more complex and Tezos focused library, which is what Taquito is in the web ecosystem.

On a side note, we're currently working on such a library in Swift that should help you decode the payloads.
