### ISSUE TITLE
[Bug]: Memory leaks

### ISSUE THREAD

**Issue by simonmcl** [airgap-it/beacon-ios-sdk#17]
As mentioned on slack, i've encountered an issue where the below callback / print out gets executed twice whenever I add a Peer:

```
beaconClient?.add([.p2p(peer)], completion: { result in
	switch result {
		case .success():
			print("peer added success")
					
			completion(true)
					
		case .failure(_):
			completion(false)
	}
})
```

Digging through it and a few other issues I ran the leak inspector and found a few leaks while starting beacon, removing peers/permissions and trying to add a new peer:

![Screenshot 2022-05-11 at 15 06 57](https://user-images.githubusercontent.com/8058386/168081008-e4dc25e0-89dc-498c-800c-2e3c10dd32f3.png)

**Comment by jsamol** [comment]
Fixed in `v3.1.2`.
