### ISSUE TITLE
[Feature Request]: Return callbacks to the main thread

### ISSUE THREAD

**Issue by simonmcl** [airgap-it/beacon-ios-sdk#18]
Most of the callbacks used are connected to a UI event, but all callbacks are returned on a background thread. I think the majority, if not all, should be bounced back to the main thread.

Examples:
- When a request comes in, first thing I do is put a spinner on the screen to show the user that something is incoming. That means having to put a call to run on main thread at the start of every incoming request
- Removing peers / permissions are trigger via a UI button, its not something I do in the background without user action. Again my exception would be to throw up a spinner, call the code to remove and then remove the spinner and refresh
- Adding peers or permissions, again trigger by UI event

**Comment by jsamol** [comment]
Thanks for the suggestion! We've taken some time to discuss it internally but eventually decided against proceeding with the changes. We don't want to force handling anything on the main thread if it *doesn't* have to be handled on the main thread. We're leaving the choice to the developer who has the context and a broader view of their actions and requirements.

We'll update the docs to make sure that it's always clear on what thread callbacks are executed, though.
