### ISSUE TITLE
Mocking

### ISSUE THREAD

**Issue by simonmcl** [airgap-it/beacon-ios-sdk#3]
Can you expose the underlying URLSession object to devs so that the requests can be mocked easily?

If you expose a URLSession parameter, I can just create a Mock instance of URLProtocol, pass it a list of URLs and file names, and then everything is mocked throughout my app/library with a handful of lines of code. Without that, it means having to subclass and duplicate many classes and understand business logic in order to be able to implement unit tests around the code. Multiple this by 10 third party libraries and it becomes a lot of effort, and going forward having to update whenever a function definition is changed

**Comment by jsamol** [comment]
We've just released `v2.0.0` which comes with a change that allows to provide an external `URLSession` through `Beacon.Connection.P2PConfiguration`. You can pass it while creating a new `Beacon.Client` instance:
```swift
let configuration = Beacon.Client.Configuration(name: "MyApp", connections: [.p2p(.init(urlSession: myURLSession))])
let beaconClient = Beacon.Client.create(with: configuration) { ... }
```
