### ISSUE TITLE
Disconnect / stop listening

### ISSUE THREAD

**Issue by simonmcl** [airgap-it/beacon-ios-sdk#6]
I'm confused how to manage beacon within the iOS app lifecycle events (e.g. going to background, foreground, suspend etc.). I have created a Beacon.Client instance, told it to connect, and I registered a function to listen for incoming events. How do I disconnect / stop listening when the app goes into background and reconnect when it's reopened? I can't see any public disconnect / stop listening function, only the ability to remove a peer entirely

**Comment by jsamol** [comment]
As of `v2.0.0` there are now 4 methods in `Beacon.Client` to manage the connection: `Beacon.Client#connect`, `Beacon.Client#disconnect`, `Beacon.Client#pause` and `Beacon.Client#resume`.

Calling `Beacon.Client#pause` will suspend all ongoing and scheduled network calls as well as all registered listeners, BUT it'll keep the listeners in memory, so later everything can be resumed with a call to `Beacon.Client#resume`.

Stopping the connection with `Beacon.Client#disconnect` cancels all calls and removes all listeners, resulting in an almost irreversible state. To bring the connection back, it needs to be restarted with `Beacon.Client#connect` and `Beacon.Client.listenOnRequest`.

I hope this covers what you needed 😄 

If you encounter any issues with those methods or have a question/request for something related to them, please open a new issue. I'm closing this one.

**Comment by simonmcl** [comment]
@jsamol thanks for the quick turn around on this. Be a little while for I have a cycle to test it, but looks like exactly what I need. Thanks
