### ISSUE TITLE
Fix CocoaPods support

### ISSUE THREAD

**Issue by jsamol** [airgap-it/beacon-ios-sdk#8]
_As mentioned below, the current CocoaPods setup is invalid and must be fixed._

> ## iOS
> We're not planning on releasing to CocoaPods. But yes, it's possible to add the dependency directly from GitHub. I'll make sure the pod spec file is up to date and update README with detailed information on how to do it.

I have tried current podspec file from [here](https://github.com/airgap-it/beacon-ios-sdk/tree/3.0.1-beta.1). There are several building issues due to the fact that Cocoapods builds single framework from subspecs: 
- duplicate file AppMetadata.swift
-  not needed 'import BeaconCore' in subspecs (for example, BeaconBlockchainSubstrate) 
-  various definition duplicates, for example, ExtendedDependencyRegistry

Looks like we need a separate podspecs instead of subspecs.

_Originally posted by @ERussel in https://github.com/airgap-it/beacon-android-sdk/issues/4#issuecomment-1043010999_

**Comment by jsamol** [comment]
@ERussel As of [`3.0.1-beta.3`](https://github.com/airgap-it/beacon-ios-sdk/tree/3.0.1-beta.3) each package has a separate podspec as you suggested. Let me know it works as expected now.

**Comment by ERussel** [comment]
It works as expected! Thank you!
